title: Aryan Nanda
email: nandaaryan823@gmail.com
description:
author: Aryan Nanda
baseurl: "/Blogs"
url: "https://AryanNanda17.github.io"

# Social Profiles
twitter_username:
github_username: AryanNanda17
facebook_username:
instagram_username: aryan__nanda
linkedin_username: aryan-nanda-25b32224b

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
